joint_trajectory_controller:
  type: "joint_trajectory_controller/JointTrajectoryController"
  joint_names:
    - "joint1"  
  gains:
    joint1:
      p: 100.0
      i: 0.0
      d: 10.0
  state_publish_rate: 50  
  action_monitor_rate: 30  
  constraints:
    goal_time: 1.0  
    path_tolerance:
      position: 0.01
      velocity: 0.1
    goal_tolerance:
      position: 0.01
      velocity: 0.1
