points: [-3.14,-2.0, 0.0,1.0,3.14, 2.0,0.0,-1.5]
segment_time: 3.0
frequency: 200
kp: 10.0
kd: 1.0
torque: 0.2
pos_gain: 10.0      
vel_gain: 0.1    
ff_gain: 1.0 
v_max: 8.0     
loop: true
loop_count: 2
record_all_loops: true 
control_mode: "velocity"  #velocity   position
